### ISSUE TITLE
Extensions should use .scratch() rather than .data()

### ISSUE THREAD

**Issue by maxkfranz** [iVis-at-Bilkent/cytoscape.js-view-utilities#1]
`.data('foo')` can lead to collisions with user data.  `.scratch('viewUtil').foo` does not.

**Comment by selimfirat** [comment]
Done and it is better now. Thanks.

**Comment by maxkfranz** [comment]
Great.  It should also be namespaced by the extension name.  See http://js.cytoscape.org/#ele.scratch

**Comment by ugurdogrusoz** [comment]
@maxkfranz Could you confirm all is in order now?

**Comment by maxkfranz** [comment]
Looks good!  

Might want to put the null check in a helper function for brevity

**Comment by selimfirat** [comment]
Thanks for advice, done.
