### ISSUE TITLE
Restricting functionality to selected elements only

### ISSUE THREAD

**Issue by mafar** [iVis-at-Bilkent/cytoscape.js-view-utilities#14]
Is it possible to restrict which nodes can be candidate for view-utilities functionality.
For example I only want parent nodes to be able to hide or show with  js-view-utilities
functionality

Similar functionality is provided with -node-resize plugin  with which one is able to apply controls over desired nodes only

```
// https://github.com/iVis-at-Bilkent/cytoscape.js-node-resize provides 
isNoControlsMode: function (node) { return node.is(".noControlsMode") }, // no controls - do not draw grapples
```

**Comment by ugurdogrusoz** [comment]
@mafar you could process nodes to be hidden and eliminate the ones you don't want to hide yourself

**Comment by mafar** [comment]
@ugurdogrusoz 
I understand , u mean ```neighbor: function(node){``` serves the same purpose.
