### ISSUE TITLE
Support for defining multiple highlighting styles 

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-view-utilities#15]
User should be able to define up to four different highlighting styles for nodes and edges in options. Let's name those options as "highlighted" (the current one), "highlighted2", "highlighted3" and "highlighted4". After user defined different styles, a sample usage should be as follows:
```
var instance = cy.viewUtilities(options); 
instance.highlight(eles, "highlighted2");
```
If user doesn't define the second parameter in the above example that indicates the highlighting style, then the style in "highlighted" should be used as default.

**Comment by ugurdogrusoz** [comment]
Can we use the following colors for highlighting in specified order please: blue(same as the one used in highlighting in Newt), green(4,240,106), yellow(245,230,99), and red(191,6,3)

**Comment by MobiZaman** [comment]
The support for multiple highlighting styles (as specified above) has been added. But instead of taking two arguments in the highlight function, a single object containing the elements and highlighting option is received.
`var instance = cy.viewUtilities(options); 
instance.highlight({eles: eles, option: "highlighted2"});`
If only the elements are sent to the function, then the default blue highlight color is used.
`instance.highlight(eles);`

**Comment by hasanbalci** [comment]
It seems ok. Please also correct the default edge options in README.md.

**Comment by hasanbalci** [comment]
One question: Before, removeHighlights() was working when we don't give any parameter to the function, but now when I tried, it gives error. Can you also check this problem?

**Comment by MobiZaman** [comment]
Yes removeHighlights() function requires a parameter right now. I will change it back and I will also update the read me file.

**Comment by MobiZaman** [comment]
Both of the above tasks have been completed. The removeHighlights() function now works if no parameter is provided to it.

**Comment by MobiZaman** [comment]
The unhighlight option has been completely removed from the code.

**Comment by hasanbalci** [comment]
Since unhiglighted option is removed and that operation can be done using other highlighting options, I think we don't need the instance.unhighlight(eles) and instance.unhighlightNeighbors(eles) functions in the api anymore. Those functions should be removed and readme should also be updated accordingly.

**Comment by MobiZaman** [comment]
The unhighlighting functions have been removed and the read me file has also been updated.
