### ISSUE TITLE
Can not change settings

### ISSUE THREAD

**Issue by canbax** [iVis-at-Bilkent/cytoscape.js-view-utilities#17]
I want to change highlight border-width based on user input. I set default at the first time.

`let options = {
      node: {
        highlighted: C.HIGHLIGHTED_NODE_1,
        highlighted2: C.HIGHLIGHTED_NODE_2,
        highlighted3: C.HIGHLIGHTED_NODE_3,
        // options object has some other properties ...
cy.viewUtilities(options)`

I change options.node.hightlighted3 and then I call `cy.viewUtilities(options)` again but I see settings did not changed

**Comment by hasanbalci** [comment]
@canbax Can you test and verify the fix in unstable branch?

**Comment by canbax** [comment]
Yes. I see that I can change options. Thanks. I'm waiting for master branch
