### ISSUE TITLE
eles.show() and eles.hide() are already defined and can't be overridden

### ISSUE THREAD

**Issue by maxkfranz** [iVis-at-Bilkent/cytoscape.js-view-utilities#2]
You'll get an error if you try to override existing functions with an extension.  You'll have to use different names for `.show()` and `.hide()`, for example.

**Comment by selimfirat** [comment]
It's not programmatically prohibited (if you mean this, there may be a bug) but may cause indirect error from inside cytoscape.js usages. I just changed them to hideEles/showEles.
