### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-view-utilities#20]
Let's update Cytoscape.js dependency as ^3.2.0 instead of ^2.7.0 both in README and package.json. This is required if user wants to apply cose-bilkent layout as post-processing. 

Also, let's use the latest version of the cose-bilkent in the demo files.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Please verify and close if OK

**Comment by hasanbalci** [comment]
@nasimsaleh Can we remove `natives` from the dependencies? It is not necessary for this extension.
