### ISSUE TITLE
Choice of highlight color

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-view-utilities#25]
- [x] 1. Let's please update the [undoable demo](https://raw.githack.com/iVis-at-Bilkent/cytoscape.js-view-utilities/unstable/demo-undoable.html) as well.
Let's do the following in both demos:
- [x] 2. Let's rename "Highlight Elements" to "Highlight Selected"
- [x] 3.Let's leave some space before "Highlight Selected"
- [x] 4. We also need to update the README (changes in the API)

**Comment by ugurdogrusoz** [comment]
2: Done in regular demo but not in Undoable demo
4: The API should not assume the highlight is done with just change of color, the user might prefer other ways to highlight (using opacity of objects for instance). So, let's change the API naming to be more general, not necessarily restricted to color. For instance, `changeNumColor` should be renamed as `changeNumHighlight`. 
- [x] 5. Let's try to get this working with older versions of Cytsocape as well (especially for Newt). Currently Newt crashes on highlighting with an error in the Console.

**Comment by ugurdogrusoz** [comment]
4: The current API is still very specific to change border color and width for highlights. The user might instead say change the fill color on highlight of a node instead or change its opacity. So let's also make the following two API more **generic** (`getHighlightStyles` and `changeHighlightStyle` with more general parameters?):
- `instance.getHighlightColors()`
- `instance.changeHighlightColor(idx, color, borderWidth = 3)`

**Comment by ugurdogrusoz** [comment]
I noticed a problem: if you select a highlighted node its border color is not selection color (black) but still the selection color.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Please review

**Comment by hasanbalci** [comment]
In README, I think the parameter information of `instance.highlightNeighbors` should be same with the parameter information of `instance.highlight` function. There is also a small typo in the explanation of `var instance = cy.viewUtilities(options)`, it should be "if you want to override" instead of "if you want tp override".

**Comment by hasanbalci** [comment]
It seems ok now.
