### ISSUE TITLE
Undo problem emerging after multiple highlights

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/cytoscape.js-view-utilities#3]
In undoable demo file,
I highlghted the neighbours of Jerry and get the following screen,

![highlight_neighbours_jerry](https://cloud.githubusercontent.com/assets/6534865/16734750/539b27e4-478f-11e6-85a1-964e6c440a4a.PNG)

Then I highlighted the neighbours of Kramer and get the following screen,

![highlight_neighbours_krammer](https://cloud.githubusercontent.com/assets/6534865/16734801/7c7aae3c-478f-11e6-9732-02dad7cfccf9.PNG)

Finally I performed an undo operation and get the following result,

![undo_after_highlights](https://cloud.githubusercontent.com/assets/6534865/16734826/90bc20ce-478f-11e6-85de-b1ab2436db9b.PNG)

I think that something must be wrong with undo operation performed after multiple times highlights.

**Comment by selimfirat** [comment]
It seems fixed now. May you confirm it? Then I can publish it on npm.

**Comment by metincansiper** [comment]
It seems to be fixed, thanks. When you publish it you can close the issue.

**Comment by selimfirat** [comment]
Published.
