### ISSUE TITLE
Adding a new dependency breaks existing applications

### ISSUE THREAD

**Issue by canbax** [iVis-at-Bilkent/cytoscape.js-view-utilities#35]
This might be intentional but adding a new dependency breaks existing applications.

https://github.com/iVis-at-Bilkent/cytoscape.js-view-utilities/blob/b9e217783dccc81a068a4751651604e7564ed29b/package.json#L44

The users should install `geometric` to use view-utilities.

This error will be shown in all the applications when they deleted `node_modules` folder and make an `npm install`. Adding `geometric` inside `devDependencies` might fix the issue.

**Comment by canbax** [comment]
I still get the error. We are only using `pointInPolygon`,  `polygonIntersectsPolygon`, and, `polygonInPolygon` methods of the library. I think we can just copy-paste these methods from the original source and use it. It is an open-source and MIT licensed project. https://github.com/HarryStevens/geometric

**Comment by msalihaltun** [comment]
I will probably revert the commit referenced above since `geometric` is not a dev dependency anyways. We might just copy the methods from the original source, but first I want to get to the bottom of this error since `geometric` is listed inside the `package.json` file but is not being installed for applications that use the extension.

**Comment by ugurdogrusoz** [comment]
If we decide to lift code from a different library, make sure to check its license and make sure to keep a reference to the original library code in our extension as well.

**Comment by msalihaltun** [comment]
This was probably a `package-lock` file related issue (of other applications). Doesn't happen when installing fresh or when `package-lock` file is deleted together with `node_modules`. It shouldn't happen anymore after the `package-lock` is 'fixed' after installing with this dependency. It is still a bit confusing to me how it all worked out.

We have the option to use the library's internal functions in our code as @canbax pointed out, but it is more about 10 functions than 3. And we wouldn't receive any updates to the library functions in the future I suppose. On the other hand, this can help us remove an external dependency which is good.

Thoughts on this @hasanbalci @ugurdogrusoz @canbax ?

**Comment by canbax** [comment]
I think it could stay like this. It's my bad to delete the `node_modules` folder but not delete `package-lock.json` file. That's how I get an error message.

But I think having less dependency is always better for a library.

**Comment by ugurdogrusoz** [comment]
Let's keep the library as is I think.

**Comment by msalihaltun** [comment]
Okay, we keep it as is then. This can be closed now I think.
