### ISSUE TITLE
Highlighting a selected node unselects it

### ISSUE THREAD

**Issue by dshenderson** [iVis-at-Bilkent/cytoscape.js-view-utilities#38]
I should be able to highlight or unhighlight a selected node with that node remaining selected, but when a node becomes highlighted it no longer is selected.

**Comment by msalihaltun** [comment]
@ugurdogrusoz it seems we implemented this highlight with unselect explicity, is there any particular reason? It can be removed without problems.

**Comment by msalihaltun** [comment]
Hi @dshenderson, I made a fix for this issue. You can check it out in the [unstable demo](https://raw.githack.com/iVis-at-Bilkent/cytoscape.js-view-utilities/unstable/demo.html).

**Comment by dshenderson** [comment]
@msalihaltun @ugurdogrusoz Thank you very much for resolving this so promptly! Looking forward to the release.

**Comment by dshenderson** [comment]
@msalihaltun @ugurdogrusoz  Any idea when we can expect a release, so that I can implement this fix? Thanks!

**Comment by ugurdogrusoz** [comment]
@dshenderson we don't have the resources to do frequent releases. the next release might be as late as this summer. please base your application on the unstable branch (the specific commit that fixes this issue). despite the branch name, it should be rather stable.
