### ISSUE TITLE
Error when initialising

### ISSUE THREAD

**Issue by ghost** [iVis-at-Bilkent/cytoscape.js-view-utilities#39]
Hello - if I initialise with non empty highlightStyles and selectStyles, I get the following error:

TypeError: Cannot read property 'selector' of undefined

![Screen Shot 2021-08-06 at 5 58 10 pm](https://user-images.githubusercontent.com/22624099/128477302-e0c3bc45-7010-4c5e-b54d-080af9467bce.png)

If I initialise with  empty highlightStyles and selectStyles it initialises OK.

Here is some test code that shows options that work and options that do not work:

```
import cytoscape from "cytoscape";
import viewUtilities from "cytoscape-view-utilities";
viewUtilities(cytoscape); // register extension
const cy = cytoscape()
const optionsWorking = {
    highlightStyles: [],
    selectStyles: {},
};
const optionsNotWorking = {
    highlightStyles: [
        {node: {'border-color': '#0b9bcd', 'border-width': 3},
            edge: {
                'line-color': '#0b9bcd',
                'source-arrow-color': '#0b9bcd',
                'target-arrow-color': '#0b9bcd',
                'width': 3
            }
        },
        {node: {'border-color': '#04f06a', 'border-width': 3},
            edge: {
                'line-color': '#04f06a',
                'source-arrow-color': '#04f06a',
                'target-arrow-color': '#04f06a',
                'width': 3
            }
        },
    ],
    selectStyles: {
        node: {'border-color': 'black', 'border-width': 3, 'background-color': 'lightgrey'},
        edge: {'line-color': 'black', 'source-arrow-color': 'black', 'target-arrow-color': 'black', 'width': 3}
    },
};

let api = cy.viewUtilities(optionsWorking);

export default cy;

```

Can anyone suggest please what might be the issue?

thanks!

**Comment by hasanbalci** [comment]
@bootrino Since view-utilities is a UI extension, it doesn't make sense to use it in headless cytoscape instances. In other words, you should provide a [container](https://js.cytoscape.org/#init-opts/container) to your `cytoscape()`. If you still want to run cytoscape headlessly, then you need to set [styleEnabled](https://js.cytoscape.org/#init-opts/styleEnabled) option to `true` to be able to use this extension.

**Comment by ghost** [comment]
@hasanbalci hmm OK thanks for the prompt reply.

Actually I mount the container a bit later instead of during initialisation like this:

            cy.mount(container.current)

Thanks for the pointer though - I'll see if I can find a way to initialise cytoscape.js-view-utilities after my mount command.
