### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by maxkfranz** [iVis-at-Bilkent/cytoscape.js-view-utilities#5]
This extension should really follow the convention that it returns an object with its API, and only registers a single function per core and per collection with the same name as the extension.

e.g.

``` js
cy.viewutil().search(...);

cy.$('#foo').viewutil().highlight();
```

Otherwise, your extension can collide with other extensions or new APIs added to the core.

**Comment by metincansiper** [comment]
@maxkfranz I made the requested changes. If there is no problem we can close the issue.

**Comment by maxkfranz** [comment]
Looks good 👍
