### ISSUE TITLE
TypeError: viewUtilities is not a function

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/cytoscape.js-view-utilities#6]
Please try the following link: https://tonicdev.com/56dd390fafca530d006e8a75/57b6c2b4138af81400a64b3d

**Comment by ugurdogrusoz** [comment]
Please fix this @metincansiper

**Comment by metincansiper** [comment]
The problem was related to an error in 'gulp build' command. It seems to be fixed now. @mrsfy would you publish a new version or would you enable me to publish this extension to npm?

**Comment by selimfirat** [comment]
I just published and enabled you to publish for all extensions.

**Comment by metincansiper** [comment]
Thanks.
