### ISSUE TITLE
demo.html throws "ReferenceError: cytoscape is not defined"

### ISSUE THREAD

**Issue by KonradHoeffner** [iVis-at-Bilkent/cytoscape.js-view-utilities#7]
After a fresh clone, opening demo.html in Firefox 54 throws the following errors:

```
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.  demo.html
ReferenceError: cytoscape is not defined[Learn More]  demo.html:42:21
	<anonymous> file:///tmp/cytoscape.js-view-utilities/demo.html:42:21
```

I think the problem is that this import does not exist: http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-latest/cytoscape.min.js

I could get it to work by replacing the link with https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.1.2/cytoscape.min.js.

**Comment by hasanbalci** [comment]
It should be ok now, please can you verify and close the issue?

**Comment by KonradHoeffner** [comment]
Thanks for the lightning fast fix, it works now!
